sudo: required

arch:
  repos:
      - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
    - gcc
    - boost
    - cmake
  script:
    - git clone https://github.com/jingjinghack/mcstatus
    - cd mcstatus
    - mkdir build
    - cd build
    - cmake ..
    - make

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
