sudo: required

arch:
  repos:
    - papyros=https://mirror.csclub.uwaterloo.ca/archlinux/$repo/os/$arch
  packages:
    - gcc
    - boost
    - cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

script:
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
